/* ================= 量子数据：Gaussian Cube 电子密度导入（纯解析/采样模块，Node 可校验） =================
   第一版只支持「单标量场」电子密度 Cube（.cube/.cub，Gaussian cubegen / Multiwfn 导出）：
   · 读取两行注释、原子数与原点、三个网格轴、原子列表、体素标量值
   · 原子单位（bohr）→ Å（1 bohr = 0.529177210903 Å，CODATA 2018），统一按网格包围盒中心居中
   · 明确拒绝：负原子数 / 多数据集（DSET_ID）、多轨道合并、非法头部、NaN/Infinity、整体非正密度
   · 本模块不依赖 THREE / DOM —— 可在 Node 中直接校验（tools/validate-cube.mjs） */

/* ---------- 集中配置：文件与体素上限（保守、展示在导入面板） ---------- */
const CUBE_LIMITS = {
  maxFileBytes: 64 * 1024 * 1024, // 64 MB：典型电子密度 cube 为 1–20 MB
  maxVoxels: 4 * 1000 * 1000,     // 400 万体素（≈159³ 网格）：超大网格请先在 Multiwfn 降低精度
};
const BOHR_TO_ANGSTROM = 0.529177210903; // CODATA 2018

/* ---------- 元素符号表（原子序数 → 符号；公开标准数据） ---------- */
const ELEMENT_SYMBOLS = ("H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og").split(" ");
function symbolOfZ(z){
  const i = Math.round(z) - 1;
  return (i >= 0 && i < ELEMENT_SYMBOLS.length) ? ELEMENT_SYMBOLS[i] : ("X" + Math.round(z));
}

/* ---------- 共价半径（Å，仅用于「视觉单键推断」，不可当作量子计算输出的键级） ---------- */
const COVALENT_RADIUS = {
  H:0.31, He:0.28, Li:1.28, Be:0.96, B:0.84, C:0.76, N:0.71, O:0.66, F:0.57,
  Ne:0.58, Na:1.66, Mg:1.41, Al:1.21, Si:1.11, P:1.07, S:1.05, Cl:1.02, Ar:1.06,
  K:2.03, Ca:1.76, Sc:1.70, Ti:1.60, V:1.53, Cr:1.39, Mn:1.39, Fe:1.32, Co:1.26,
  Ni:1.24, Cu:1.32, Zn:1.22, Ga:1.22, Ge:1.20, As:1.19, Se:1.20, Br:1.20, Kr:1.16,
  Rb:2.20, Sr:1.95, Y:1.90, Zr:1.75, Nb:1.64, Mo:1.54, Tc:1.47, Ru:1.46, Rh:1.42,
  Pd:1.39, Ag:1.45, Cd:1.44, In:1.42, Sn:1.39, Sb:1.39, Te:1.38, I:1.39, Xe:1.40,
};
function covalentRadius(el){
  return COVALENT_RADIUS[el] !== undefined ? COVALENT_RADIUS[el] : 0.90;
}

/* ---------- 小工具（自包含，避免依赖 03_core，便于 Node 校验） ---------- */
function cubeClamp(v, a, b){ return v < a ? a : (v > b ? b : v); }
function cubeMulberry32(seed){
  let a = seed >>> 0;
  return function (){
    a += 0x6D2B79F5;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function cubeGauss(rand){
  const u = Math.max(rand(), 1e-9);
  const v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}
function cubeError(code, message){
  const e = new Error(message);
  e.cubeCode = code;
  return e;
}

/* ---------- 字段类型估计（诚实启发式，不假装识别 HOMO/LUMO） ----------
   Cube 格式没有可靠的属性标签：Multiwfn 头部不写属性名（只写 "Generated by
   Multiwfn" + 网格点数）；Gaussian cubegen 的注释行可能写（Density / Orbital N /
   ESP…）。因此：
   · 注释行关键词命中 → 高置信标注（仅当明确出现；"density" 需排除
     "functional/theory" 等上下文避免误判 DFT 字样）
   · 数据统计：负值占比可靠区分「非负字段」vs「带符号字段」（>20% 负值）；
     峰值量级/有界性 → 低-中置信提示（电子密度 / ELF 等）
   · 绝不声称能区分 HOMO vs LUMO、轨道 vs ESP：真实带符号文件振幅不可靠
     （实测 ASPIRIN_HOMO47.cub 的 |值|max ≈ 5.3e5，无法用振幅分轨道/ESP） */
const FIELD_HINT_KEYS = {
  orbital:   ["orbital", "homo", "lumo", "wave function", "wavefunction", "molecular orbital", "mo("],
  esp:       ["esp", "electrostatic potential", "mep"],
  elf:       ["elf", "electron localization function"],
  laplacian: ["laplacian", "lap of"],
  // CP2K / 其它 DFT 代码导出的 Hartree（库仑）势场：长程、处处非零、常带符号，
  // 不是电子密度——按「势场」诚实标注并路由到带符号（双色相位）模式
  hartree:   ["hartree"],
};
function estimateCubeFieldType(stats){
  const text = ((stats.title || "") + " " + (stats.comment || "")).toLowerCase();
  const hit = function (keys){ return keys.some(function (k){ return text.indexOf(k) >= 0; }); };
  const hasDensityHint = hit(["electron density", "scf density", "total density", "spin density", "core density", "density difference", "rho("])
    || (hit(["density"]) && !hit(["functional", "theory", "potential", "orbital"]));
  let hintKey = null;
  if (hit(FIELD_HINT_KEYS.orbital)) hintKey = "orbital";
  else if (hit(FIELD_HINT_KEYS.hartree)) hintKey = "hartree";
  else if (hit(FIELD_HINT_KEYS.esp)) hintKey = "esp";
  else if (hit(FIELD_HINT_KEYS.elf)) hintKey = "elf";
  else if (hit(FIELD_HINT_KEYS.laplacian)) hintKey = "laplacian";
  else if (hasDensityHint) hintKey = "density";
  const negFrac = stats.nVox > 0 ? stats.negVox / stats.nVox : 0;
  if (hintKey) return { type: hintKey, confidence: "high", negFrac: negFrac, maxAbs: stats.maxAbs, vMax: stats.vMax };
  if (negFrac > 0.20) return { type: "signed_field", confidence: "high", negFrac: negFrac, maxAbs: stats.maxAbs, vMax: stats.vMax };
  if (negFrac <= 0.01){
    if (stats.vMax > 2) return { type: "electron_density_likely", confidence: "medium", negFrac: negFrac, maxAbs: stats.maxAbs, vMax: stats.vMax };
    return { type: "nonnegative_field", confidence: "low", negFrac: negFrac, maxAbs: stats.maxAbs, vMax: stats.vMax };
  }
  return { type: "mixed_small_negative", confidence: "low", negFrac: negFrac, maxAbs: stats.maxAbs, vMax: stats.vMax };
}

/* ---------- 惰性文本 token 流（避免一次性 split 出超大数组） ---------- */
const _WS = " \t\n\r\f\v";
function cubeTokenize(text, from){
  let i = from;
  return function (){
    while (i < text.length && _WS.indexOf(text[i]) >= 0) i++;
    if (i >= text.length) return null;
    let j = i;
    while (j < text.length && _WS.indexOf(text[j]) < 0) j++;
    const tok = text.slice(i, j);
    i = j;
    return tok;
  };
}
/* 轻量统计：从 from 起剩余 token 个数（只扫字符、不分配字符串，用于消歧“数据集计数前缀”） */
function cubeCountTokens(text, from){
  let i = from, count = 0;
  while (true){
    while (i < text.length && _WS.indexOf(text[i]) >= 0) i++;
    if (i >= text.length) break;
    count++;
    while (i < text.length && _WS.indexOf(text[i]) < 0) i++;
  }
  return count;
}
function cubeNextLine(text, from){
  let i = from;
  while (i < text.length && text[i] !== "\n") i++;
  return { line: text.slice(from, i), next: i < text.length ? i + 1 : i };
}

/* ---------- Cube 解析（纯函数；抛 cubeError，携带用户可理解的 message/code） ---------- */
function parseCubeText(text, opts){
  // opts.allowSigned = true → 保留原始带符号体素值（轨道模式）；false（默认）→ 截断负值（密度模式）
  const allowSigned = !!(opts && opts.allowSigned);
  if (typeof text !== "string" || !text.length){
    throw cubeError("EMPTY", "文件为空或无法读取。请确认导出的是有效的 Gaussian Cube 文件。");
  }
  let off = 0;
  const l1 = cubeNextLine(text, off); off = l1.next;
  const l2 = cubeNextLine(text, off); off = l2.next;
  const title = l1.line.trim();
  const comment = l2.line.trim();
  const l3 = cubeNextLine(text, off); off = l3.next;
  const h3 = l3.line.trim().split(/\s+/);
  if (h3.length < 4){
    throw cubeError("BAD_HEADER", "文件头错误：第 3 行应为「原子数 原点x 原点y 原点z」（当前：\"" + l3.line.trim() + "\"）。");
  }
  const natomsRaw = Number(h3[0]);
  if (!Number.isFinite(natomsRaw) || natomsRaw === 0){
    throw cubeError("BAD_HEADER", "文件头错误：原子数无效（" + h3[0] + "）。");
  }
  if (natomsRaw < 0){
    throw cubeError("MULTI_DATASET", "该 Cube 为多数据集文件（负原子数 " + natomsRaw + " / DSET_ID）。请在 Multiwfn 中仅导出单独的电子密度 Cube（single data set）后重试。");
  }
  const natoms = Math.round(natomsRaw);
  const originB = [Number(h3[1]), Number(h3[2]), Number(h3[3])];
  if (!originB.every(Number.isFinite)){
    throw cubeError("BAD_HEADER", "文件头错误：原点坐标无效。");
  }
  const dims = [0, 0, 0], axesB = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
  for (let k = 0; k < 3; k++){
    const lk = cubeNextLine(text, off); off = lk.next;
    const hk = lk.line.trim().split(/\s+/);
    if (hk.length < 4) throw cubeError("BAD_DIMS", "文件头错误：网格轴 " + (k + 1) + " 行无效（应为「点数 vx vy vz」）。");
    const n = Number(hk[0]);
    if (!Number.isInteger(n) || n <= 0) throw cubeError("BAD_DIMS", "网格尺寸无效：" + hk[0] + "（应为正整数）。");
    dims[k] = n;
    axesB[k] = [Number(hk[1]), Number(hk[2]), Number(hk[3])];
    if (!axesB[k].every(Number.isFinite)) throw cubeError("BAD_DIMS", "文件头错误：网格轴 " + (k + 1) + " 向量无效。");
  }
  const nVox = dims[0] * dims[1] * dims[2];
  if (nVox > CUBE_LIMITS.maxVoxels){
    throw cubeError("TOO_MANY_VOXELS", "体素数量 " + nVox.toLocaleString() + " 超过上限 " + CUBE_LIMITS.maxVoxels.toLocaleString() + "（约 159³ 网格）。请在 Multiwfn 中降低网格精度（Grid spacing 调大）后重试。");
  }
  // 原子列表（原子单位）
  const atomsB = [];
  for (let a = 0; a < natoms; a++){
    const la = cubeNextLine(text, off); off = la.next;
    const ha = la.line.trim().split(/\s+/);
    if (ha.length < 5) throw cubeError("BAD_ATOMS", "原子行 " + (a + 1) + " 格式错误（应为「原子序数 电荷 x y z」）。");
    const z = Math.round(Number(ha[0]));
    const q = Number(ha[1]);
    const p = [Number(ha[2]), Number(ha[3]), Number(ha[4])];
    if (!Number.isFinite(z) || !Number.isFinite(q) || !p.every(Number.isFinite)){
      throw cubeError("BAD_ATOMS", "原子行 " + (a + 1) + " 数值无效。");
    }
    atomsB.push({ z: z, q: q, pos: p });
  }
  // 数据区（体素标量值，x 变化最快：index = ix + nx·iy + nx·ny·iz）
  const dataRaw = new Float32Array(nVox);
  let idx = 0, nonFinite = false;
  // Multiwfn 等工具可能以「数据集计数」整数开头。消歧规则（可解释、不误伤普通数据）：
  //   先轻量统计剩余 token 数 nRem（不分配字符串）：
  //   · nRem = 1 + nVox 且首 token 为裸整数 → 数据集计数前缀（=1 单数据集通过；≠1 即多数据集）
  //   · nRem = 1 + k·nVox（k≥2）且首 token 为裸整数 → 明确多数据集（Multiwfn 多轨道合并）
  //   · 其余情况 → 首 token 就是普通数据值（标准 cubegen/Gaussian 密度值总是 E 格式，非裸整数）
  const nRem = cubeCountTokens(text, off);
  const nextTok = cubeTokenize(text, off);
  let tok = nextTok();
  if (tok !== null && /^-?\d+$/.test(tok)){
    const k = (nRem - 1) / nVox;
    if (Number.isInteger(k) && k >= 2){
      throw cubeError("MULTI_DATASET", "该 Cube 含 " + parseInt(tok, 10) + " 个数据集（多数据集 / 多轨道合并）。请在 Multiwfn 中仅导出单独的电子密度 Cube（single data set）后重试。");
    }
    if (k === 1){
      const firstInt = parseInt(tok, 10);
      if (firstInt !== 1){
        throw cubeError("MULTI_DATASET", "该 Cube 含 " + firstInt + " 个数据集（多数据集 / 多轨道合并）。请在 Multiwfn 中仅导出单独的电子密度 Cube（single data set）后重试。");
      }
      tok = nextTok(); // 跳过数据集计数 "1"
    }
  }
  let count = 0, negVox = 0, maxAbs = 0;
  while (tok !== null){
    if (idx < nVox){
      const v = Number(tok);
      if (!Number.isFinite(v)) nonFinite = true;
      else {
        const a = Math.abs(v);
        if (a > maxAbs) maxAbs = a;
        if (v < 0) negVox++;
        // 密度模式：负值截断为 0；轨道模式：保留原始带符号值（相位信息）
        dataRaw[idx] = allowSigned ? v : (v < 0 ? 0 : v);
      }
      idx++;
    }
    count++;
    tok = nextTok();
  }
  if (nonFinite){
    throw cubeError("NON_FINITE", "体素数据包含 NaN 或 Infinity，无法作为密度场。请重新导出 Cube 文件。");
  }
  if (count !== nVox){
    throw cubeError("DATA_COUNT", "体素数据数量不匹配：应有 " + nVox.toLocaleString() + " 个值，实际读取 " + count.toLocaleString() + " 个。");
  }
  // 统计：vMax/vSum 一律按「幅值 |v|」（密度模式负值已截断，等价于原逻辑）
  let vMax = 0, vSum = 0;
  for (let i = 0; i < nVox; i++){
    const v = dataRaw[i];
    const m = v < 0 ? -v : v;
    if (m > vMax) vMax = m;
    vSum += m;
  }
  // 字段类型估计（注释行关键词 + 数据统计；诚实标注置信度，不假装识别 HOMO/LUMO）
  const fieldType = estimateCubeFieldType({ title: title, comment: comment, negVox: negVox, nVox: nVox, vMax: vMax, maxAbs: maxAbs });
  if (vMax <= 0){
    throw cubeError("NON_POSITIVE", "电子密度整体为非正值（最大值 ≤ 0），无法作为密度场。请确认导出的是电子密度（electron density）而非带正负号的轨道（orbital）Cube。");
  }
  // 带符号字段：电子密度处处非负。默认（密度模式）拒绝 >20% 负值的带符号字段并引导；
  // allowSigned（轨道模式）保留原始相位，交给上层按轨道模式渲染。
  if (!allowSigned && negVox / nVox > 0.20){
    const zh = fieldType.type === "orbital" ? "（注释行标注为分子轨道）"
      : fieldType.type === "esp" ? "（注释行标注为静电势 ESP）"
      : fieldType.type === "laplacian" ? "（注释行标注为 Laplacian）"
      : fieldType.type === "elf" ? "（注释行标注为 ELF）"
      : "（可能是分子轨道 HOMO/LUMO 或静电势 ESP）";
    throw cubeError("SIGNED_FIELD", "该 Cube 含大量负值（" + (negVox / nVox * 100).toFixed(1) + "% 体素为负），不是电子密度" + zh + "。请在 Multiwfn 中导出 electron density（Main function 1）后再导入。");
  }
  // ---- 体素数据顺序自动检测 ----
  // 标准 Gaussian Cube 为 x-fastest（index = ix + nx·iy + nx·ny·iz），但部分工具/数据
  // 库（实测：本萘密度文件）用 z-fastest 等其它顺序。布局错了会把分子密度峰打散成
  // 弥漫壳层 → 云弥散。检测法：真实密度在原子核处取峰，用原子位置试 6 种布局，
  // 取「原子处密度均值」最大者为正确布局；非 x-fastest 时重排为标准顺序。
  const nx0 = dims[0], ny0 = dims[1], nz0 = dims[2];
  const _orders = {
    xyz: function (a, b, c){ return a + nx0 * b + nx0 * ny0 * c; },
    xzy: function (a, b, c){ return a + nx0 * c + nx0 * nz0 * b; },
    yxz: function (a, b, c){ return b + ny0 * a + nx0 * ny0 * c; },
    yzx: function (a, b, c){ return b + ny0 * c + ny0 * nz0 * a; },
    zxy: function (a, b, c){ return c + nz0 * a + nz0 * nx0 * b; },
    zyx: function (a, b, c){ return c + nz0 * b + nz0 * ny0 * a; },
  };
  let dataOrder = "xyz", bestMean = -1, xyzMean = 0;
  const ax0 = Math.abs(axesB[0][0]) || 1e-9, ay0 = Math.abs(axesB[1][1]) || 1e-9, az0 = Math.abs(axesB[2][2]) || 1e-9;
  for (const name in _orders){
    const f = _orders[name];
    let s = 0, cnt = 0;
    for (const a of atomsB){
      const ix0 = Math.round((a.pos[0] - originB[0]) / ax0);
      const iy0 = Math.round((a.pos[1] - originB[1]) / ay0);
      const iz0 = Math.round((a.pos[2] - originB[2]) / az0);
      // 取原子 3×3×3 邻域（π 轨道在原子处有节面，邻域内仍有信号；也降低网格对位敏感性）
      for (let dx = -1; dx <= 1; dx++){
        for (let dy = -1; dy <= 1; dy++){
          for (let dz = -1; dz <= 1; dz++){
            const ix = ix0 + dx, iy = iy0 + dy, iz = iz0 + dz;
            if (ix < 0 || ix >= nx0 || iy < 0 || iy >= ny0 || iz < 0 || iz >= nz0) continue;
            const i = f(ix, iy, iz);
            if (i >= 0 && i < nVox){ const v = dataRaw[i]; s += v < 0 ? -v : v; cnt++; }
          }
        }
      }
    }
    if (cnt > 0){
      const mean = s / cnt;
      if (name === "xyz") xyzMean = mean;
      if (mean > bestMean){ bestMean = mean; dataOrder = name; }
    }
  }
  if (dataOrder !== "xyz" && bestMean > Math.max(xyzMean * 1.5, 1e-30)){
    // 重排为标准 x-fastest
    const perm = new Float32Array(nVox);
    const f = _orders[dataOrder];
    for (let iz = 0; iz < nz0; iz++){
      for (let iy = 0; iy < ny0; iy++){
        for (let ix = 0; ix < nx0; ix++){
          perm[ix + nx0 * iy + nx0 * ny0 * iz] = dataRaw[f(ix, iy, iz)];
        }
      }
    }
    dataRaw.set(perm);
  }
  return {
    title: title, comment: comment,
    natoms: natoms, originB: originB, axesB: axesB, dims: dims, nVox: nVox,
    atomsB: atomsB, dataRaw: dataRaw,
    vMin: 0, vMax: vMax, vSum: vSum, vMean: vSum / nVox,
    negVox: negVox, maxAbs: maxAbs, fieldType: fieldType,
    signed: allowSigned,
    dataOrder: dataOrder, // 检测到的原始数据顺序（xyz=标准 x-fastest）
  };
}

/* ---------- CubeVolume：体数据（单位换算 + 居中 + 采样 + 统计） ---------- */
/* 支持非零原点与完整三轴仿射变换（不假设正方体、不以原点为中心）：
   世界坐标 p 与分数坐标 f 满足  p = origin + f·A  （A 的列 = 三个轴向量）
   采样时用逆矩阵 f = A⁻¹·(p − origin) 做三线性插值，边界外钳制 */
function buildCubeVolume(parsed, opts){
  // opts.mode: "density"（默认）| "orbital"——轨道模式按 |ψ| 做截断/采样，保留相位（符号）用于双色渲染
  const signed = !!(opts && opts.mode === "orbital");
  const dims = parsed.dims, axesB = parsed.axesB, originB = parsed.originB;
  const axes = axesB.map(function (v){ return [v[0] * BOHR_TO_ANGSTROM, v[1] * BOHR_TO_ANGSTROM, v[2] * BOHR_TO_ANGSTROM]; });
  const origin = [originB[0] * BOHR_TO_ANGSTROM, originB[1] * BOHR_TO_ANGSTROM, originB[2] * BOHR_TO_ANGSTROM];
  // 网格中心（世界 Å）→ 统一居中（分子居中，网格与原子一起平移）
  const center = [
    origin[0] + ((dims[0] - 1) / 2) * axes[0][0] + ((dims[1] - 1) / 2) * axes[1][0] + ((dims[2] - 1) / 2) * axes[2][0],
    origin[1] + ((dims[0] - 1) / 2) * axes[0][1] + ((dims[1] - 1) / 2) * axes[1][1] + ((dims[2] - 1) / 2) * axes[2][1],
    origin[2] + ((dims[0] - 1) / 2) * axes[0][2] + ((dims[1] - 1) / 2) * axes[1][2] + ((dims[2] - 1) / 2) * axes[2][2],
  ];
  const orgC = [origin[0] - center[0], origin[1] - center[1], origin[2] - center[2]];
  const atoms = parsed.atomsB.map(function (a, i){
    return {
      idx: i, z: a.z, el: symbolOfZ(a.z), q: a.q,
      pos: [
        a.pos[0] * BOHR_TO_ANGSTROM - center[0],
        a.pos[1] * BOHR_TO_ANGSTROM - center[1],
        a.pos[2] * BOHR_TO_ANGSTROM - center[2],
      ],
    };
  });
  // 逆变换矩阵（3×3，Cramer 法则）
  const m = axes;
  const det = m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
            - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
            + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]);
  if (!Number.isFinite(det) || Math.abs(det) < 1e-12){
    throw cubeError("DEGENERATE_AXES", "网格轴线性相关（行列式 ≈ 0），无法构成有效体数据。请重新导出 Cube。");
  }
  const inv = [
    [ (m[1][1] * m[2][2] - m[1][2] * m[2][1]) / det, -(m[0][1] * m[2][2] - m[0][2] * m[2][1]) / det,  (m[0][1] * m[1][2] - m[0][2] * m[1][1]) / det ],
    [-(m[1][0] * m[2][2] - m[1][2] * m[2][0]) / det,  (m[0][0] * m[2][2] - m[0][2] * m[2][0]) / det, -(m[0][0] * m[1][2] - m[0][2] * m[1][0]) / det ],
    [ (m[1][0] * m[2][1] - m[1][1] * m[2][0]) / det, -(m[0][0] * m[2][1] - m[0][1] * m[2][0]) / det,  (m[0][0] * m[1][1] - m[0][1] * m[1][0]) / det ],
  ];
  const nx = dims[0], ny = dims[1], nz = dims[2], nxy = nx * ny;
  const dataRaw = parsed.dataRaw;
  function sample(x, y, z){
    const dx = x - orgC[0], dy = y - orgC[1], dz = z - orgC[2];
    let fx = inv[0][0] * dx + inv[0][1] * dy + inv[0][2] * dz;
    let fy = inv[1][0] * dx + inv[1][1] * dy + inv[1][2] * dz;
    let fz = inv[2][0] * dx + inv[2][1] * dy + inv[2][2] * dz;
    fx = cubeClamp(fx, 0, nx - 1.0001);
    fy = cubeClamp(fy, 0, ny - 1.0001);
    fz = cubeClamp(fz, 0, nz - 1.0001);
    const ix = Math.floor(fx), iy = Math.floor(fy), iz = Math.floor(fz);
    const tx = fx - ix, ty = fy - iy, tz = fz - iz;
    // 文件体素顺序：x 最快 → index = ix + nx·iy + nx·ny·iz
    const i000 = ix + nx * iy + nxy * iz;
    const c000 = dataRaw[i000], c100 = dataRaw[i000 + 1], c010 = dataRaw[i000 + nx], c110 = dataRaw[i000 + nx + 1];
    const c001 = dataRaw[i000 + nxy], c101 = dataRaw[i000 + nxy + 1], c011 = dataRaw[i000 + nxy + nx], c111 = dataRaw[i000 + nxy + nx + 1];
    const c00 = c000 * (1 - tx) + c100 * tx, c10 = c010 * (1 - tx) + c110 * tx;
    const c01 = c001 * (1 - tx) + c101 * tx, c11 = c011 * (1 - tx) + c111 * tx;
    const c0 = c00 * (1 - ty) + c10 * ty, c1 = c01 * (1 - ty) + c11 * ty;
    return c0 * (1 - tz) + c1 * tz;
  }
  // 边界（世界 Å，居中后）
  const lo = [orgC[0], orgC[1], orgC[2]];
  const hi = [
    orgC[0] + (nx - 1) * axes[0][0] + (ny - 1) * axes[1][0] + (nz - 1) * axes[2][0],
    orgC[1] + (nx - 1) * axes[0][1] + (ny - 1) * axes[1][1] + (nz - 1) * axes[2][1],
    orgC[2] + (nx - 1) * axes[0][2] + (ny - 1) * axes[1][2] + (nz - 1) * axes[2][2],
  ];
  // 低密度截断（可解释、稳定）：
  //   cutoff = max(95% 总质量阈值, 0.1% × 峰值)
  //   · 95% 质量阈值（对数直方图）自适应紧包围盒，保留分子包络；
  //   · 0.1% × 峰值下限（CUBE_CUT_FRACTION）兜底：松包围盒/非零背景（Multiwfn
  //     粗网格常见 ~1e-3 a.u.）时，纯质量阈值会跌破背景、把整盒噪声都保留 → 云弥散。
  //     该下限保证背景（典型 ≤ 1e-3×峰值）被排除，云始终贴分子形状。
  const nVox = parsed.nVox;
  const rhoMax = parsed.vMax; // 幅值峰值（轨道模式 = max|ψ|）
  // 截断：cutoff = max(95% 总质量阈值, 峰值下限)
  //   · 质量阈值（对数直方图）自适应；轨道模式叠加等值面惯例下限：
  //     |ψ| ≥ 3% × max|ψ|（CUBE_ORB_ISO，Gaussian/Multiwfn/VMD 轨道等值面惯例），
  //     使轨道瓣边缘清晰、低幅值尾晕不铺满全盒
  const CUBE_CUT_FRACTION = signed ? 1e-4 : 1e-3;
  const CUBE_ORB_ISO = 0.03;
  const magOf = function (i){ const v = dataRaw[i]; return signed && v < 0 ? -v : v; };
  const logMax = Math.log1p(rhoMax);
  const HIST_BINS = 512;
  const hist = new Float64Array(HIST_BINS);
  const binOf = function (v){ return v <= 0 ? 0 : Math.min(HIST_BINS - 1, Math.floor(Math.log1p(v) / logMax * HIST_BINS)); };
  for (let i = 0; i < nVox; i++) hist[binOf(magOf(i))] += magOf(i);
  const totalMass = parsed.vSum; // 幅值总和（Σ|v|）
  let massCut = 0, acc = 0;
  for (let b = HIST_BINS - 1; b >= 0; b--){
    const binMass = hist[b];
    if (acc + binMass >= totalMass * 0.95){
      const need = totalMass * 0.95 - acc;
      const frac = binMass > 0 ? cubeClamp(need / binMass, 0, 1) : 0;
      const binLo = (b / HIST_BINS) * logMax, binHi = ((b + 1) / HIST_BINS) * logMax;
      massCut = Math.expm1(binLo + (binHi - binLo) * (1 - frac));
      break;
    }
    acc += binMass;
  }
  const cutoff = signed ? Math.max(massCut, rhoMax * CUBE_ORB_ISO) : Math.max(massCut, rhoMax * CUBE_CUT_FRACTION);
  // 密度模式的「分子包络空间上限」：电子密度超出分子 ~3.5Å 基本可忽略，但超大松盒的
  // 低幅值尾晕质量可能占总量 10%+，纯质量阈值会把它保留 → 云铺满全盒（弥散）。
  // 丢弃「距分子中心超过 R_mol + 3.5Å」的体素（紧盒不触发；轨道模式保留完整瓣，靠相机取景）。
  // 注意：分子以原子包围盒中心为参考——直接用原子半径 Rmol 更稳（网格可能偏离分子）。
  const SPATIAL_MARGIN = 3.5;
  let Rmol = 0;
  for (let ai = 0; ai < atoms.length; ai++){
    const a = atoms[ai].pos;
    const rr = a[0] * a[0] + a[1] * a[1] + a[2] * a[2];
    if (rr > Rmol) Rmol = rr;
  }
  Rmol = Math.sqrt(Rmol);
  const capR2 = (Rmol + SPATIAL_MARGIN) * (Rmol + SPATIAL_MARGIN);
  // 采样 CDF（仅保留幅值 ≥ cutoff 且（密度模式）在分子包络内的体素；权重 = log1p(幅值/cutoff − 1)）
  // 同时累计 kept 体素的幅值总和 → 分子平均电子密度 rhoMean（元数据展示用）
  // 以及「加权密度分位」直方图 → rhoCDF（颜色分位展开：按粒子权重把密度映射到整条色图，
  // 保证任何分布下颜色都有可见变化——修复电子密度模式下云呈单色的现象）
  const cdf = new Float64Array(nVox);
  const wHist = new Float64Array(HIST_BINS);
  let totalW = 0, kept = 0, keptSum = 0;
  for (let i = 0; i < nVox; i++){
    let inCap = true;
    if (!signed){
      const iz = Math.floor(i / nxy);
      const rem = i - iz * nxy;
      const iy = Math.floor(rem / nx);
      const ix = rem - iy * nx;
      const px = orgC[0] + (ix + 0.5) * axes[0][0] + (iy + 0.5) * axes[1][0] + (iz + 0.5) * axes[2][0];
      const py = orgC[1] + (ix + 0.5) * axes[0][1] + (iy + 0.5) * axes[1][1] + (iz + 0.5) * axes[2][1];
      const pz = orgC[2] + (ix + 0.5) * axes[0][2] + (iy + 0.5) * axes[1][2] + (iz + 0.5) * axes[2][2];
      inCap = px * px + py * py + pz * pz <= capR2;
    }
    const v = magOf(i);
    if (v >= cutoff && inCap){
      const w = Math.log1p(v / cutoff - 1);
      totalW += w; kept++; keptSum += v;
      wHist[binOf(v)] += w;
    }
    cdf[i] = totalW;
  }
  const rhoMean = kept > 0 ? keptSum / kept : rhoMax;
  // 加权密度分位 CDF（0..1）：rhoCDF[b] = 至 bin b 的累计权重占比
  const rhoCDF = new Float64Array(HIST_BINS);
  let wAcc = 0;
  for (let b = 0; b < HIST_BINS; b++){
    wAcc += wHist[b];
    rhoCDF[b] = totalW > 0 ? wAcc / totalW : 0;
  }
  return {
    title: parsed.title, comment: parsed.comment,
    fileName: parsed.fileName || null,
    atoms: atoms, natoms: atoms.length,
    origin: orgC, axes: axes, dims: dims, nVox: nVox,
    data: dataRaw,
    inv: inv,
    sample: sample,
    bounds: { min: lo, max: hi },
    rhoMax: rhoMax, rhoMean: rhoMean, rhoCut: cutoff, keptVoxels: kept, keptFraction: kept / nVox,
    rhoCDF: rhoCDF, rhoBins: HIST_BINS, rhoLogMax: logMax,
    cdf: cdf, totalW: totalW,
    vMean: parsed.vMean, vSum: parsed.vSum,
    negVox: parsed.negVox, maxAbs: parsed.maxAbs, fieldType: parsed.fieldType,
    mode: signed ? "orbital" : "density", isSigned: signed,
  };
}

/* ---------- 按真实密度权重采样粒子目标分布（替代 computeField 伪造分布） ---------- */
/* 大分子（环糊精等几十上百原子）固定粒子预算下，纯密度加权会把粒子集中在重原子核区，
   低密度原子（尤其 H）几乎无粒子 → 云看起来稀疏/不够用。两阶段采样：
   · 密度加权部分（1−CUBE_ATOM_BASELINE）×count：严格按体素密度比例（颜色=局部相对密度）
   · 原子覆盖部分 CUBE_ATOM_BASELINE×count：均匀选原子 + 高斯散布（σ≈0.7Å），
     保证每个原子上都有基准粒子；颜色/亮度仍按该点局部相对密度（同一色标）
   仅当原子数 ≥ CUBE_ATOM_MIN_ATOMS 时启用基准（小分子密度云本身已覆盖所有原子） */
const CUBE_ATOM_MIN_ATOMS = 16;
const CUBE_ATOM_BASELINE = 0.3;
const CUBE_ATOM_SIGMA = 0.7;
function sampleCloudCube(vol, count){
  const cdf = vol.cdf, totalW = vol.totalW;
  const nx = vol.dims[0], ny = vol.dims[1], nz = vol.dims[2], nxy = nx * ny;
  const org = vol.origin, ax = vol.axes;
  // 颜色密度：加权密度分位展开（直方图均衡）——
  //   dAttr = rhoCDF(log1p(ρ))（按粒子权重累计的分位，0..1 单调）
  //   · 粒子颜色按密度分位铺满整条色图：低密度端暗/冷、高密度端亮/暖；
  //   · 任何密度分布下颜色都有可见变化（修复电子密度模式云呈单色的现象）；
  //   · 轨道模式同按 |ψ| 分位（相位双色仍按符号取 LUT）。
  const rhoCDF = vol.rhoCDF, rhoBins = vol.rhoBins, rhoLogMax = vol.rhoLogMax;
  const dAttrOf = function (mag){
    const x = Math.log1p(Math.max(mag, vol.rhoCut));
    const xc = Math.min(x / rhoLogMax, 1);
    const b = Math.min(rhoBins - 1, Math.floor(xc * rhoBins));
    const binLo = b / rhoBins, binHi = (b + 1) / rhoBins;
    const t = (xc - binLo) / (binHi - binLo);
    const below = b > 0 ? rhoCDF[b - 1] : 0;
    return cubeClamp(below + (rhoCDF[b] - below) * t, 0, 1);
  };
  const rand = cubeMulberry32(20260828);
  const pos = new Float32Array(count * 3);
  const size = new Float32Array(count);
  const bright = new Float32Array(count);
  const density = new Float32Array(count);
  const sign = new Float32Array(count); // 轨道相位：+1/−1（密度模式恒 0）
  const seed = new Float32Array(count * 3);
  const delay = new Float32Array(count);
  const nAtoms = vol.atoms.length;
  const baseline = nAtoms >= CUBE_ATOM_MIN_ATOMS ? CUBE_ATOM_BASELINE : 0;
  const nDens = Math.floor(count * (1 - baseline));
  const setP = function (i, px, py, pz, psi){
    const mag = psi < 0 ? -psi : psi;
    const dAttr = dAttrOf(mag);
    pos[i * 3] = px; pos[i * 3 + 1] = py; pos[i * 3 + 2] = pz;
    size[i] = 0.55 + rand() * 0.75 + 0.35 * Math.min(mag / vol.rhoMax, 1);
    bright[i] = cubeClamp(0.14 + 0.28 * dAttr + rand() * 0.16, 0.05, 0.55);
    density[i] = dAttr;
    sign[i] = vol.isSigned ? (psi < 0 ? -1 : 1) : 0;
    seed[i * 3] = rand(); seed[i * 3 + 1] = rand(); seed[i * 3 + 2] = rand();
    delay[i] = 0;
  };
  for (let i = 0; i < nDens; i++){
    const r = rand() * totalW;
    let lo = 0, hi = cdf.length - 1;
    while (lo < hi){ const mid = (lo + hi) >> 1; if (cdf[mid] < r) lo = mid + 1; else hi = mid; }
    const li = lo;
    const iz = Math.floor(li / nxy);
    const rem = li - iz * nxy;
    const iy = Math.floor(rem / nx);
    const ix = rem - iy * nx;
    const u = rand(), v = rand(), w = rand();
    const px = org[0] + (ix + u) * ax[0][0] + (iy + v) * ax[1][0] + (iz + w) * ax[2][0];
    const py = org[1] + (ix + u) * ax[0][1] + (iy + v) * ax[1][1] + (iz + w) * ax[2][1];
    const pz = org[2] + (ix + u) * ax[0][2] + (iy + v) * ax[1][2] + (iz + w) * ax[2][2];
    setP(i, px, py, pz, vol.sample(px, py, pz)); // 轨道模式 = 带符号 ψ；密度模式 = ρ ≥ 0
  }
  for (let i = nDens; i < count; i++){
    const a = vol.atoms[Math.floor(rand() * nAtoms)];
    const px = a.pos[0] + cubeGauss(rand) * CUBE_ATOM_SIGMA;
    const py = a.pos[1] + cubeGauss(rand) * CUBE_ATOM_SIGMA;
    const pz = a.pos[2] + cubeGauss(rand) * CUBE_ATOM_SIGMA;
    setP(i, px, py, pz, vol.sample(px, py, pz));
  }
  return { pos: pos, size: size, bright: bright, density: density, sign: sign, seed: seed, delay: delay };
}

/* ---------- 视觉单键推断（元素 + 距离 + 共价半径；仅供骨架流动路径，不是 QM 键级） ---------- */
function inferSingleBonds(atoms){
  const bonds = [];
  for (let i = 0; i < atoms.length; i++){
    for (let j = i + 1; j < atoms.length; j++){
      const a = atoms[i].pos, b = atoms[j].pos;
      const d = Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
      const rc = covalentRadius(atoms[i].el) + covalentRadius(atoms[j].el);
      if (d < rc + 0.45) bonds.push({ i: i, j: j, order: 1 });
    }
  }
  return bonds;
}

/* ---------- 由 CubeVolume 构建渲染用分子对象（原子 + 推断单键） ---------- */
function buildCubeMolecule(vol){
  const atoms = vol.atoms.map(function (a, i){
    return { el: a.el, pos: a.pos.slice(), key: "cube#" + i, atomIdx: i, fragId: -1, localIdx: -1 };
  });
  const bonds = inferSingleBonds(atoms);
  return { atoms: atoms, bonds: bonds, fragments: [], isCube: true };
}
