/* ================= 依赖导入 ================= */
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { EffectComposer } from "three/addons/postprocessing/EffectComposer.js";
import { RenderPass } from "three/addons/postprocessing/RenderPass.js";
import { UnrealBloomPass } from "three/addons/postprocessing/UnrealBloomPass.js";
import { OutputPass } from "three/addons/postprocessing/OutputPass.js";

/* ================= 粒子着色器 ================= */
/* 噪声实现：Ashima Arts / Stefan Gustavson 的 3D simplex noise（MIT License，保留原出处）。
   curl noise 采用 Bridson 2007 有限差分法。 */
const CLOUD_VERTEX = [
"uniform float uTime;",
"uniform float uTransStart;",
"uniform float uTransDur;",
"uniform float uPixelRatio;",
"uniform float uScale;",
"uniform float uParticleSize;",
"uniform float uNoiseAmp;",
"uniform float uBreathAmp;",
"uniform float uFlowAmp;",
"uniform float uCloudAlpha;",
"uniform vec3 uCenter;",
"uniform vec3 uAnchor;",
"attribute vec4 aOldProps;",
"attribute vec4 aSeed;",
"attribute vec4 aProps;",
"attribute vec3 aPath0;",
"attribute vec3 aPath1;",
"attribute vec3 aPath2;",
"attribute vec3 aPath3;",
"attribute vec3 aPath4;",
"attribute vec3 aPath5;",
"attribute vec3 aPath6;",
"attribute vec3 aPath7;",
"attribute vec3 aPath8;",
"attribute float aPathCount;",
"varying float vBright;",
"varying float vDensity;",
"",
"vec3 mod289(vec3 x){ return x - floor(x * (1.0/289.0)) * 289.0; }",
"vec4 mod289(vec4 x){ return x - floor(x * (1.0/289.0)) * 289.0; }",
"vec4 permute(vec4 x){ return mod289(((x*34.0)+1.0)*x); }",
"vec4 taylorInvSqrt(vec4 r){ return 1.79284291400159 - 0.85373472095314 * r; }",
"float snoise(vec3 v){",
"  const vec2 C = vec2(1.0/6.0, 1.0/3.0);",
"  const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);",
"  vec3 i  = floor(v + dot(v, C.yyy));",
"  vec3 x0 = v - i + dot(i, C.xxx);",
"  vec3 g = step(x0.yzx, x0.xyz);",
"  vec3 l = 1.0 - g;",
"  vec3 i1 = min(g.xyz, l.zxy);",
"  vec3 i2 = max(g.xyz, l.zxy);",
"  vec3 x1 = x0 - i1 + C.xxx;",
"  vec3 x2 = x0 - i2 + C.yyy;",
"  vec3 x3 = x0 - D.yyy;",
"  i = mod289(i);",
"  vec4 p = permute(permute(permute(",
"      i.z + vec4(0.0, i1.z, i2.z, 1.0))",
"    + i.y + vec4(0.0, i1.y, i2.y, 1.0))",
"    + i.x + vec4(0.0, i1.x, i2.x, 1.0));",
"  float n_ = 0.142857142857;",
"  vec3 ns = n_ * D.wyz - D.xzx;",
"  vec4 j = p - 49.0 * floor(p * ns.z * ns.z);",
"  vec4 x_ = floor(j * ns.z);",
"  vec4 y_ = floor(j - 7.0 * x_);",
"  vec4 x = x_ * ns.x + ns.yyyy;",
"  vec4 y = y_ * ns.x + ns.yyyy;",
"  vec4 h = 1.0 - abs(x) - abs(y);",
"  vec4 b0 = vec4(x.xy, y.xy);",
"  vec4 b1 = vec4(x.zw, y.zw);",
"  vec4 s0 = floor(b0)*2.0 + 1.0;",
"  vec4 s1 = floor(b1)*2.0 + 1.0;",
"  vec4 sh = -step(h, vec4(0.0));",
"  vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy;",
"  vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww;",
"  vec3 p0 = vec3(a0.xy, h.x);",
"  vec3 p1 = vec3(a0.zw, h.y);",
"  vec3 p2 = vec3(a1.xy, h.z);",
"  vec3 p3 = vec3(a1.zw, h.w);",
"  vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2,p2), dot(p3,p3)));",
"  p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w;",
"  vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);",
"  m = m * m;",
"  return 42.0 * dot(m*m, vec4(dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3)));",
"}",
"vec3 snoiseVec3(vec3 x){",
"  float s  = snoise(x);",
"  float s1 = snoise(vec3(x.y - 19.1, x.z + 33.4, x.x + 47.2));",
"  float s2 = snoise(vec3(x.z + 74.2, x.x - 124.5, x.y + 99.4));",
"  return vec3(s, s1, s2);",
"}",
"vec3 curlNoise(vec3 p){",
"  const float e = 0.12;",
"  vec3 dx = vec3(e, 0.0, 0.0);",
"  vec3 dy = vec3(0.0, e, 0.0);",
"  vec3 dz = vec3(0.0, 0.0, e);",
"  vec3 px0 = snoiseVec3(p - dx);",
"  vec3 px1 = snoiseVec3(p + dx);",
"  vec3 py0 = snoiseVec3(p - dy);",
"  vec3 py1 = snoiseVec3(p + dy);",
"  vec3 pz0 = snoiseVec3(p - dz);",
"  vec3 pz1 = snoiseVec3(p + dz);",
"  float x = py1.z - py0.z - pz1.y + pz0.y;",
"  float y = pz1.x - pz0.x - px1.z + px0.z;",
"  float z = px1.y - px0.y - py1.x + py0.x;",
"  vec3 c = vec3(x, y, z) * (1.0 / (2.0 * e));",
"  return c / (length(c) + 0.0001);",
"}",
"float easeInOut(float t){ return t*t*(3.0 - 2.0*t); }",
"void main(){",
"  float tt = uTransDur > 0.001 ? clamp((uTime - uTransStart - aSeed.w*0.6*uTransDur)/uTransDur, 0.0, 1.0) : 1.0;",
"  float e = easeInOut(tt);",
"  float es = mix(aOldProps.x, aProps.x, e);",
"  // 沿 σ 骨架折线路径流动：所有跨原子迁移一律途经原子序列（折点恰在原子处），",
"  // 骨架弯折处粒子严格跟随折线，不切角",
"  float pp = e * aPathCount;",
"  vec3 rest;",
"  if (pp <= 1.0) rest = mix(aPath0, aPath1, pp);",
"  else if (pp <= 2.0) rest = mix(aPath1, aPath2, pp - 1.0);",
"  else if (pp <= 3.0) rest = mix(aPath2, aPath3, pp - 2.0);",
"  else if (pp <= 4.0) rest = mix(aPath3, aPath4, pp - 3.0);",
"  else if (pp <= 5.0) rest = mix(aPath4, aPath5, pp - 4.0);",
"  else if (pp <= 6.0) rest = mix(aPath5, aPath6, pp - 5.0);",
"  else if (pp <= 7.0) rest = mix(aPath6, aPath7, pp - 6.0);",
"  else if (pp <= 8.0) rest = mix(aPath7, aPath8, pp - 7.0);",
"  else rest = aPath8;",
"  float ttg = uTransDur > 0.001 ? clamp((uTime - uTransStart)/uTransDur, 0.0, 1.0) : 0.0;",
"  float env = sin(3.14159265*ttg);",
"  // 过渡期间路径粒子适度收紧但保留弥散：带状电子流贴骨架流动，又不被键模型完全遮挡",
"  float routed = step(1.5, aPathCount);",
"  float tight = mix(1.0, 0.55, env * routed);",
"  float n = snoise(aSeed.xyz*6.31 + rest*1.8 + vec3(0.0, uTime*0.22, 0.0));",
"  vec3 wob = curlNoise(rest*1.65 + aSeed.xyz*2.4 + vec3(0.0, uTime*0.15, uTime*0.11)) * uNoiseAmp * (0.5 + 0.5*n) * tight;",
"  vec3 rd = rest - uCenter;",
"  float rl = length(rd) + 0.001;",
"  vec3 rdir = rd / rl;",
"  float breath = sin(uTime*1.1 + aSeed.y*6.2831853) * uBreathAmp * smoothstep(0.0, 2.6, rl) * tight;",
"  vec3 disp = position - aPath0;",
"  float dl = length(disp) + 0.0001;",
"  vec3 ddir = disp / dl;",
"  // 定向涌动：沿迁移方向推进（像电子流），路径粒子几乎无垂直分量",
"  vec3 flow = ddir * uFlowAmp * env * 0.5 * (1.0 - 0.7 * routed);",
"  flow += cross(ddir, curlNoise(rest*2.9 + vec3(0.0, uTime*0.3, uTime*0.2))) * uFlowAmp * env * 0.18 * tight;",
"  vec3 pos = rest + wob + rdir*breath + flow;",
"  vec4 mv = modelViewMatrix * vec4(pos, 1.0);",
"  gl_Position = projectionMatrix * mv;",
"  gl_PointSize = clamp(uParticleSize * es * uScale / max(-mv.z, 0.001), 1.0, 90.0);",
"  float fadeIn = smoothstep(0.0, 1.4, uTime);",
"  vBright = mix(aOldProps.y, aProps.y, e) * uCloudAlpha * fadeIn;",
"  vDensity = mix(aOldProps.z, aProps.z, e);",
"}",
].join("\n");

const CLOUD_FRAGMENT = [
"uniform sampler2D uDensityTex;",
"uniform float uDensGamma;",
"varying float vBright;",
"varying float vDensity;",
"void main(){",
"  vec2 uv = gl_PointCoord*2.0 - 1.0;",
"  float d2 = dot(uv, uv);",
"  if (d2 > 1.0) discard;",
"  float d = sqrt(d2);",
"  float a = pow(1.0 - d, 2.4);",
"  a *= smoothstep(1.0, 0.3, d);",
"  vec3 col = texture2D(uDensityTex, vec2(pow(clamp(vDensity, 0.0, 1.0), uDensGamma), 0.5)).rgb;",
"  gl_FragColor = vec4(col, a * vBright);",
"}",
].join("\n");
